### ISSUE TITLE
bug: Some namespaces are not deleted when we uninstall syncer yaml resources

### ISSUE THREAD

**Issue by cmoulliard** [kcp-dev/kcp#1910] opened 2022-09-07 14:55 UTC
### Describe the bug

Some namespaces are not deleted when we uninstall the syncer yaml resources.

Here are the namespaces that we can see
```
k get ns
NAME                 STATUS   AGE
default              Active   95m
kcp-0ac93yu10t91     Active   93m
kcp-2okhpr5g4ci3     Active   93m
kube-node-lease      Active   95m
kube-public          Active   95m
kube-system          Active   95m
local-path-storage   Active   95m
```
after we executed
```
kubectl delete syncer-kind.yml
```

### Steps To Reproduce

1. Create a kind cluster
2. Generate the syncer yaml file `KUBECONFIG=KCP_KUBECONFIG kubectl kcp workload sync kindy --syncer-image ghcr.io/kcp-dev/kcp/syncer:v0.8.0 -o syncer-kind.yml`
3. Apply the yaml file against the target cluster `KUBECONFIG=KUBE_CONFIG kubectl apply -f syncer-kind.yml`
4. Wait till the pod is up and running
5. Clean up: `KUBECONFIG=KUBE_CONFIG kubectl delete -f syncer-kind.yml`

### Expected Behaviour

All the `kcp-*` should be deleted

**Comment by ncdc** [comment] 2022-09-07 14:59
I'm not sure we necessarily want to remove content that was synced from kcp to the physical cluster when the syncer is deleted. I think if you want to delete that, you need to delete the content in kcp, and the syncer handles deleting it from the physical cluster. If you delete the syncer, maybe you're going to recreate it - there's no way for us to know that, and I'm not sure we want content deletion to be a side effect of deleting the syncer.

@davidfestal @sttts

**Comment by ncdc** [comment] 2022-09-08 13:20
All `kcp-*` workspaces in a physical cluster have a `internal.workload.kcp.dev/cluster` on them that can be used to identify them.

(The way to list workspaces is using `kubectl get workspaces`. The plugin is being updated)

**Comment by cmoulliard** [comment] 2022-09-08 14:42
> The way to list workspaces is using `kubectl get workspaces`. The plugin is being updated

This is not really easy to find ALL the workspaces to be deleted as it is needed to navigate through all the hierarchy in order to figure out the ws to be deleted
```
KUBECONFIG=_tmp/.kcp/admin.kubeconfig k get workspaces
No resources found
KUBECONFIG=_tmp/.kcp/admin.kubeconfig k kcp ws ..
Current workspace is "root:org1".
KUBECONFIG=_tmp/.kcp/admin.kubeconfig k get workspaces
NAME   TYPE        PHASE   URL
org2   universal   Ready   https://192.168.1.90:6443/clusters/root:org1:org2
KUBECONFIG=_tmp/.kcp/admin.kubeconfig k delete workspace org2
workspace.tenancy.kcp.dev "org2" deleted
etc
etc
```

**Comment by ncdc** [comment] 2022-09-08 19:50
> As this is something that most of the developers will not be aware

That's what documentation is for 😄.

You can technically run multiple syncers per physical cluster. So I don't think deleting all `kcp-*` workspaces without some sort of check is a good idea.

I'd probably be ok with a `kubectl kcp` plugin command of some sort that can deletesynced namespaces for a single specific syncer. It would need to list what it would do first and require user confirmation to proceed (or `--force`/`--confirm` to skip interactive).

I am however not in favor of having `kubectl delete -f syncer-kind.yml` result in the synced namespaces being deleted too.

**Comment by stevekuznetsov** [comment] 2022-09-08 22:29
What are the user flows that lead to this situation? If we assume that the workloads have some value and disruption is not something the user wants, would the user not cordon the `SyncTarget` first to get the workloads to move off? Can we maybe have some sort of deregistration process for a `SyncTarget` that would have the `syncer` in question cleaning up after itself in the physical cluster once the workloads are moved somewhere else, culminating in the `syncer` uninstalling its own `SyncTarget` and gracefully exiting?

**Comment by cmoulliard** [comment] 2022-09-09 06:54
> Can we maybe have some sort of deregistration process for a `SyncTarget`

I agree with you that we need a `deregistration` process able to clean properly kcp on a physical cluster. Something like `k kcp workload desync cluster1`. During this process the kcp namespaces on the cluster should be deleted
```
# Manual command
for ns in $(KUBECONFIG=${KUBE_CFG_PATH} k get ns -linternal.workload.kcp.dev/cluster -o name);
    do
      KUBECONFIG=${KUBE_CFG_PATH} k delete $ns
done
```
**Remark**: The syncer should be deleted/removed using `kcp workload delete cluster1`.

**Comment by davidfestal** [comment] 2023-02-22 11:06
So it seems to be a duplicate of https://github.com/kcp-dev/kcp/issues/999. Should we close this one ?

**Closed** 2023-10-26 07:14 UTC
Labels: kind/bug, help wanted, area/transparent-multi-cluster
