### ISSUE TITLE
bug: Potential for crash in apiextensions-apiserver/pkg/registry/customresource/etcd.go

### ISSUE THREAD

**Issue by kylape** [kcp-dev/kcp#2368] opened 2022-11-16 02:55 UTC
### Describe the bug

Not sure if this should be filed in the KCP project or Kube, but filing it here based on our conversation in the community call.

There is a call to `panic` at [apiextensions-apiserver/pkg/registry/customresource/etcd.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go#L71) that triggered the crash described in https://github.com/kcp-dev/kcp/issues/2304.  Best I can tell, that panic was caught by `utilruntime.HandleCrash()` from within the `Run` function of `crd_finalizer.go`.  Seems like a standard way to handle a panic, which ends in a crash of the process.

So I suppose the fix is to propagate an error instead of calling `panic`, as the `TODO` item would suggest.

Copying the stack trace here for convenience as an example of how this panic results in a crash:

```
goroutine 1885 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x42bf1c0?, 0xc01516aaa0})
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00bdaaa10?})
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x42bf1c0, 0xc01516aaa0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
k8s.io/apiextensions-apiserver/pkg/registry/customresource.newStores({{_, _}, {_, _}}, {{0xc0038e3000, 0x19}, {0xc00c7eaf00, 0x8}, {0xc00c7eba68, 0x8}}, ...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:111 +0x6cc
k8s.io/apiextensions-apiserver/pkg/registry/customresource.newREST({{_, _}, {_, _}}, {{0xc0038e3000, 0x19}, {0xc00c7eaf00, 0x8}, {0xc00c7eba68, 0x8}}, ...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:126 +0x10f
k8s.io/apiextensions-apiserver/pkg/registry/customresource.NewStorageWithCustomStore({{_, _}, {_, _}}, {{0xc0038e3000, 0x19}, {0xc00c7eaf00, 0x8}, {0xc00c7eba68, 0x8}}, ...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:50 +0x10e
k8s.io/apiextensions-apiserver/pkg/registry/customresource.NewStorage(...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:46
k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).getOrCreateServingInfoFor(0xc000630700, 0xc010b9f900)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:947 +0x1ac6
k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).GetCustomResourceListerCollectionDeleter(0xc015a28400?, 0x43ad300?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:732 +0x19
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).deleteInstances(0xc0119dd4e0?, 0xc010b9f900)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:183 +0x67
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).sync(0xc001849590, {0xc0120bb740?, 0xc00008c9b0?})
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:153 +0x807
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).processNextWorkItem(0xc001849590)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:297 +0x106
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).runWorker(0xc0039c56a0?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:285 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x1?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x413db80?, {0x4f445e0, 0xc003d74450}, 0x1, 0xc002800420)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x1?, 0x16ee6a5?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0xc002800420?, 0x0?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).Run
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:278 +0x1e5
panic: missing 'apis.kcp.dev/identity' annotation on CRD system:bound-crds|36973e4e-566d-4e58-9c7b-0901aae87636 for tlsroutes.gateway.networking.k8s.io [recovered]
	panic: missing 'apis.kcp.dev/identity' annotation on CRD system:bound-crds|36973e4e-566d-4e58-9c7b-0901aae87636 for tlsroutes.gateway.networking.k8s.io

goroutine 1885 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00bdaaa10?})
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x42bf1c0, 0xc01516aaa0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
k8s.io/apiextensions-apiserver/pkg/registry/customresource.newStores({{_, _}, {_, _}}, {{0xc0038e3000, 0x19}, {0xc00c7eaf00, 0x8}, {0xc00c7eba68, 0x8}}, ...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:111 +0x6cc
k8s.io/apiextensions-apiserver/pkg/registry/customresource.newREST({{_, _}, {_, _}}, {{0xc0038e3000, 0x19}, {0xc00c7eaf00, 0x8}, {0xc00c7eba68, 0x8}}, ...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:126 +0x10f
k8s.io/apiextensions-apiserver/pkg/registry/customresource.NewStorageWithCustomStore({{_, _}, {_, _}}, {{0xc0038e3000, 0x19}, {0xc00c7eaf00, 0x8}, {0xc00c7eba68, 0x8}}, ...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:50 +0x10e
k8s.io/apiextensions-apiserver/pkg/registry/customresource.NewStorage(...)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go:46
k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).getOrCreateServingInfoFor(0xc000630700, 0xc010b9f900)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:947 +0x1ac6
k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).GetCustomResourceListerCollectionDeleter(0xc015a28400?, 0x43ad300?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:732 +0x19
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).deleteInstances(0xc0119dd4e0?, 0xc010b9f900)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:183 +0x67
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).sync(0xc001849590, {0xc0120bb740?, 0xc00008c9b0?})
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:153 +0x807
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).processNextWorkItem(0xc001849590)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:297 +0x106
k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).runWorker(0xc0039c56a0?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:285 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x1?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x413db80?, {0x4f445e0, 0xc003d74450}, 0x1, 0xc002800420)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x1?, 0x16ee6a5?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0xc002800420?, 0x0?)
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).Run
	/home/klape/src/k8s/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:278 +0x1e5
exit status 2
```

### Steps To Reproduce

1. Check out a version of KCP prior to https://github.com/kcp-dev/kcp/issues/2304 merging
2. Build and run a local instance of KCP
3. Create an `APIExport` and corresponding `APIBinding`
4. Go to the `system:bound-crds` workspace
5. Delete the CRD that corresponds to one of the schemas associated with the API just created.  Should be easy to pick out based on the creation timestamp.

### Expected Behaviour

error is propagated and handled by controller

**Comment by ncdc** [comment] 2022-11-29 16:46
The root cause of the panic in kcp has been mitigated. Closing this issue and will file a new one to ensure we have a panic handler configured so we don't crash.

**Closed by ncdc** 2022-11-29 16:46 UTC
Labels: kind/bug
