### ISSUE TITLE
panic when adding/deleting a cluster

### ISSUE THREAD

**Issue by chirino** [kcp-dev/kcp#470] opened 2022-02-08 18:02 UTC
**Describe the bug**
KCP panic occurred when adding/deleting a cluster

**To Reproduce**
KCP had an east cluster added to it.  Then I did:
```sh
cat <<EOF | kubectl apply -f -
apiVersion: cluster.example.dev/v1alpha1
kind: Cluster
metadata:
  name: kind-west
spec:
  kubeconfig: |
$(kubectl --kubeconfig ~/.kube/config config view --flatten --minify --context kind-west|sed 's,^,    ,')
EOF

kind delete clusters east
```

got the following errors:

```
I0208 12:49:08.820757   93659 cluster.go:43] reconciling cluster "kind-east"
I0208 12:49:08.829670   93659 syncer.go:159] Set up informer for /v1, Resource=namespaces
I0208 12:49:08.829766   93659 syncer.go:159] Set up informer for /v1, Resource=services
I0208 12:49:08.829788   93659 syncer.go:159] Set up informer for networking.k8s.io/v1, Resource=ingresses
I0208 12:49:08.829825   93659 syncer.go:159] Set up informer for apps/v1, Resource=deployments
E0208 12:49:08.830589   93659 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 5854 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1028eac60, 0x1042f5da0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:74 +0x98
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:48 +0x88
panic({0x1028eac60, 0x1042f5da0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x21c
github.com/kcp-dev/kcp/pkg/syncer.(*Controller).Stop(0x1400a1ecf80)
	/Users/chirino/sandbox/kcp/pkg/syncer/syncer.go:283 +0x3c
github.com/kcp-dev/kcp/pkg/syncer.StartSyncer({0x102cc8050, 0x14004c7dc00}, 0x14002b63200, 0x1400aa16480, 0x1400a290ae0, {0x140092ffa30, 0x9}, {0x140092ff980, 0x10}, 0x2)
	/Users/chirino/sandbox/kcp/pkg/syncer/syncer.go:79 +0x1d8
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).reconcile(0x140038c6b40, {0x102cc8050, 0x14004c7dc00}, 0x1400a1cc160)
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/cluster.go:142 +0x1174
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).process(0x140038c6b40, {0x102cc8050, 0x14004c7dc00}, {0x140035987e0, 0x1c})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:277 +0x118
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).processNextWorkItem(0x140038c6b40, {0x102cc8050, 0x14004c7dc00})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:255 +0xf8
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).startWorker(...)
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:239
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start.func1()
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:235 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x140053e5f48)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:155 +0x68
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1400aa65f48, {0x102c7c540, 0x14005141500}, 0x1, 0x1400528c1e0)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:156 +0x94
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x140053e5f48, 0x989680, 0x0, 0x1, 0x1400528c1e0)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:90
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start(0x1400473b6a0, {0x102cc8050, 0x14004c7dc00})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:235 +0x1cc
created by github.com/kcp-dev/kcp/pkg/server.(*Server).installClusterController.func1
	/Users/chirino/sandbox/kcp/pkg/server/controllers.go:252 +0x440
I0208 12:49:08.830698   93659 panic.go:1038] Shutting down Cluster controller
E0208 12:49:08.830761   93659 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 5854 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1028eac60, 0x1042f5da0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:74 +0x98
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:48 +0x88
panic({0x1028eac60, 0x1042f5da0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x21c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:55 +0x104
panic({0x1028eac60, 0x1042f5da0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x21c
github.com/kcp-dev/kcp/pkg/syncer.(*Controller).Stop(0x1400a1ecf80)
	/Users/chirino/sandbox/kcp/pkg/syncer/syncer.go:283 +0x3c
github.com/kcp-dev/kcp/pkg/syncer.StartSyncer({0x102cc8050, 0x14004c7dc00}, 0x14002b63200, 0x1400aa16480, 0x1400a290ae0, {0x140092ffa30, 0x9}, {0x140092ff980, 0x10}, 0x2)
	/Users/chirino/sandbox/kcp/pkg/syncer/syncer.go:79 +0x1d8
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).reconcile(0x140038c6b40, {0x102cc8050, 0x14004c7dc00}, 0x1400a1cc160)
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/cluster.go:142 +0x1174
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).process(0x140038c6b40, {0x102cc8050, 0x14004c7dc00}, {0x140035987e0, 0x1c})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:277 +0x118
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).processNextWorkItem(0x140038c6b40, {0x102cc8050, 0x14004c7dc00})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:255 +0xf8
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).startWorker(...)
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:239
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start.func1()
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:235 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x140053e5f48)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:155 +0x68
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1400aa65f48, {0x102c7c540, 0x14005141500}, 0x1, 0x1400528c1e0)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:156 +0x94
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x140053e5f48, 0x989680, 0x0, 0x1, 0x1400528c1e0)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:90
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start(0x1400473b6a0, {0x102cc8050, 0x14004c7dc00})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:235 +0x1cc
created by github.com/kcp-dev/kcp/pkg/server.(*Server).installClusterController.func1
	/Users/chirino/sandbox/kcp/pkg/server/controllers.go:252 +0x440
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101efa11c]

goroutine 5854 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:55 +0x104
panic({0x1028eac60, 0x1042f5da0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x21c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/runtime/runtime.go:55 +0x104
panic({0x1028eac60, 0x1042f5da0})
	/opt/homebrew/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x21c
github.com/kcp-dev/kcp/pkg/syncer.(*Controller).Stop(0x1400a1ecf80)
	/Users/chirino/sandbox/kcp/pkg/syncer/syncer.go:283 +0x3c
github.com/kcp-dev/kcp/pkg/syncer.StartSyncer({0x102cc8050, 0x14004c7dc00}, 0x14002b63200, 0x1400aa16480, 0x1400a290ae0, {0x140092ffa30, 0x9}, {0x140092ff980, 0x10}, 0x2)
	/Users/chirino/sandbox/kcp/pkg/syncer/syncer.go:79 +0x1d8
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).reconcile(0x140038c6b40, {0x102cc8050, 0x14004c7dc00}, 0x1400a1cc160)
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/cluster.go:142 +0x1174
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).process(0x140038c6b40, {0x102cc8050, 0x14004c7dc00}, {0x140035987e0, 0x1c})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:277 +0x118
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).processNextWorkItem(0x140038c6b40, {0x102cc8050, 0x14004c7dc00})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:255 +0xf8
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*Controller).startWorker(...)
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:239
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start.func1()
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:235 +0x5c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x140053e5f48)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:155 +0x68
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1400aa65f48, {0x102c7c540, 0x14005141500}, 0x1, 0x1400528c1e0)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:156 +0x94
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x140053e5f48, 0x989680, 0x0, 0x1, 0x1400528c1e0)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:133 +0x88
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/chirino/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20220203192237-6b61675b7950/pkg/util/wait/wait.go:90
github.com/kcp-dev/kcp/pkg/reconciler/cluster.(*PreparedController).Start(0x1400473b6a0, {0x102cc8050, 0x14004c7dc00})
	/Users/chirino/sandbox/kcp/pkg/reconciler/cluster/controller.go:235 +0x1cc
created by github.com/kcp-dev/kcp/pkg/server.(*Server).installClusterController.func1
	/Users/chirino/sandbox/kcp/pkg/server/controllers.go:252 +0x440
```

**Expected behavior**
no panic

**Comment by ncdc** [comment] 2022-02-08 18:07
@chirino thanks for the report! This is a duplicate of #455

**Closed by ncdc** 2022-02-08 18:07 UTC
Labels: bug
