### ISSUE TITLE
bug:   error looking up virtual workspace URL  "controller-runtime-example-data.my.domain\" not found"

### ISSUE THREAD

**Issue by akoserwal** [kcp-dev/kcp#2107] opened 2022-09-30 06:12 UTC
### Describe the bug

1.664517613124293e+09   ERROR   setup   error looking up virtual workspace URL  {"api-export-name": "controller-runtime-example-data.my.domain", "error": "error getting APIExport \"controller-runtime-example-data.my.domain\": apiexports.apis.kcp.dev \"controller-runtime-example-data.my.domain\" not found"}

### Steps To Reproduce

make install 
make run

### Expected Behaviour

Name prefix defined `controller-runtime-example-`here
https://github.com/kcp-dev/controller-runtime-example/blob/main/Makefile#L193

https://github.com/kcp-dev/controller-runtime-example/blob/main/Makefile#L198

API Export created with the name: data.my.domain
https://github.com/kcp-dev/controller-runtime-example/blob/main/config/kcp/apiexport.yaml#L4

Removing the name prefix `controller-runtime-example-` or changing the API export name by adding a prefix should work.

Changing the name by adding a prefix to API export make it work but further see this issue

```
I0930 11:31:37.805817   86139 round_trippers.go:553] GET https://192.168.29.16:6443/services/apiexport/root:kafkatest/controller-runtime-example-data.my.domain/clusters/%2A/apis/data.my.domain/v1alpha1/widgets?limit=500&resourceVersion=0 404 Not Found in 7 milliseconds
```

Running with go run ./main.go --api-export-name data.my.domain

Also gives issues

```
I0930 11:41:26.675385   87311 round_trippers.go:553] GET https://192.168.29.16:6443/services/apiexport/root:kafkatest/data.my.domain/clusters/%2A/apis/data.my.domain/v1alpha1/widgets?limit=500&resourceVersion=0 404 Not Found in 1 milliseconds

```

**Comment by fgiloux** [comment] 2022-09-30 08:41
This looks like a duplicate of https://github.com/kcp-dev/controller-runtime-example/issues/22

**Comment by akoserwal** [comment] 2022-09-30 08:43
@fgiloux one additional issue I see

I0930 11:31:37.805817   86139 round_trippers.go:553] GET https://192.168.29.16:6443/services/apiexport/root:kafkatest/controller-runtime-example-data.my.domain/clusters/%2A/apis/data.my.domain/v1alpha1/widgets?limit=500&resourceVersion=0 404 Not Found in 7 milliseconds

**Comment by ncdc** [comment] 2022-09-30 11:31
Let's keep this issue in controller-runtime-example - thanks.
/close

The 404 is #1183

**Closed by ncdc** 2022-09-30 11:31 UTC
Labels: kind/bug
