### ISSUE TITLE
Link to download latest release page is not working

### ISSUE THREAD

**Issue by aslom** [kcp-dev/kcp#2647] opened 2023-01-18 17:48 UTC
Link to [latest release page](https://docs.kcp.io/kcp/main/#download-kcp) does not work as it points back to the same page https://docs.kcp.io/kcp/main/

**Comment by aslom** [comment] 2023-01-18 17:50
It should be probably hardocded to "https://github.com/kcp-dev/kcp/releases/latest" - maybe website code generation is doing something? Seems to be working fine in https://github.com/kcp-dev/kcp/blob/main/README.md#download-kcp

**Comment by mamachanko** [comment] 2023-02-04 10:49
@aslom @ncdc I think we should rename this to _“**All** links in the docs point back to the docs“_, because they do.

**Comment by ncdc** [comment] 2023-02-06 15:23
Yes, this is a duplicate of #2461 
/close

**Closed by ncdc** 2023-02-06 15:23 UTC
