### ISSUE TITLE
bug: Annotations on the SyncTarget object may break the synchronization

### ISSUE THREAD

**Issue by Roming22** [kcp-dev/kcp#2147] opened 2022-10-06 20:12 UTC
### Describe the bug

* Status of resources managed by the SyncTarget are not synced back to the kcp workspace.

### Steps To Reproduce

1. Create a SyncTarget
2. Verify that resources are synced properly
3. Update the SyncTarget to add an annotation:
```
# Add annotations required by kcp-glbc
KUBECONFIG="${kcp_kcfg}" kubectl annotate --overwrite synctarget "${sync_target_name}" featuregates.experimental.workload.kcp.dev/advancedscheduling='true'
```
4. Verify that resources (possibly only new resources?) are not synced anymore

### Expected Behaviour

Adding an annotation to the SyncTarget should not prevent the synchronization of the resources' status.

### Additional Context

This is causing an outage of Pipeline Service. While it is not a full outage as the resources are still synced to the compute, all users are impacted. Not having feedback might encourage users to spawn multiple pipelines in the hope of a transient issue, and will trigger support requests.

**Comment by stevekuznetsov** [comment] 2022-10-06 20:25
Is this any annotation, or is it specifically advanced scheduling feature gate?

**Comment by stevekuznetsov** [comment] 2022-10-06 20:26
If you remove the annotation, does syncing begin again?

**Comment by bnallapeta** [comment] 2022-10-07 05:33
@stevekuznetsov So far, we have only faced this issue with the annotation mentioned above as we were trying to use kcp glbc in our service.

No, removing the annotation is not resuming sync. In fact, I deleted the deployment and ran it again. Still no sync. Only way I could get it to work is :
- remove the synctarget
- Run kcp workload sync command
- Apply syncer.yaml on the physical cluster thus creating a new synctarget

**Comment by fgiloux** [comment] 2022-10-07 06:34
> Apply syncer.yaml on the physical cluster thus creating a new synctarget

side note: you are now likely to have a new identity hash for the apiexport of synctarget, which will require a reconfiguration of kcp-glbc

**Comment by davidfestal** [comment] 2022-10-18 08:59
Yes that's it. Exactly.

**Comment by davidfestal** [comment] 2022-10-18 12:15
Let me summarize:

The experimental Advanced Scheduling annotation added on the `SyncTarget`, and used by `kcp-glbc` is not expected to be used in a shared environment. It enables the mechanism explained by @mikenairn above where, for all resource types, the Status will not be updated in the upstream object anymore, but in SyncTarget-specific annotations.
So once this annotation has been added, you would need to have some controller setting the upstream resource status based on this annotation for all the types of resources you want to sync.

The answer to this strong but provisional limitation is the upcoming work on [Syncer Virtual Workspace Transformations + coordination controller](https://github.com/kcp-dev/kcp/issues/1898), which will supersede the Advanced Scheduling mechanism, which was only there to enable things like the `kcp-glbc` to be developed and tested before the forementioned EPIC lands.

**Comment by davidfestal** [comment] 2022-10-18 12:17
Let me close this issue then, since it is not a bug, but related to an in-progress feature

**Closed by davidfestal** 2022-10-18 12:17 UTC
Labels: kind/bug
