### ISSUE TITLE
KCP admin can create resources in workspaces that don't exist

### ISSUE THREAD

**Issue by csams** [kcp-dev/kcp#647] opened 2022-03-07 18:00 UTC
**Describe the bug**
The KCP admin can create resources in workspaces that don't exist. It might be good to have some guardrails against it even for the admin, or at least an entry in the log.

**To Reproduce**
1. Modify the kubeconfig to point to an org:workspace that doesn't have a corresponding workspace resource.
2. Create any resource in the non-existent workspace.

**Expected behavior**
The resource creation should be denied or the circumstance logged since it's not within the context of an existing workspace.

**Comment by smarterclayton** [comment] 2022-03-08 17:02
Starting a slack thread that we can summarize back here, but roughly:

1. If we allow admins to create resources outside workspaces, we need a way for admins to clean up mistakes
2. We may want to support precreating resources in a workspace via this mechanism, but we DEFINITELY don't want to leave resources from previous workspaces around when new workspaces are created

More chat here https://kubernetes.slack.com/archives/C021U8WSAFK/p1646758726804289

**Comment by sttts** [comment] 2022-03-08 17:18
I think this situation is by design and I don't think we want to invest in changing this. System:masters group membership is required to bypass workspace authorization. This is basically what root is in Linux. Ability to shoot yourself into the foot is part of that role.

In the future, we will have org admins and kcp admins as organizational roles (think of a role for service provider setup). These won't be system:masters, but would intentionally switch to some shard admin role to the privileged operations described in this issue. In other words: "admins are not admins" is something we will see much more than in Kube. I.e. the described danger won't be real in practice for normal administration of kcp.

**Comment by sttts** [comment] 2022-03-08 17:20
+1 for closing if nobody objects.

**Closed** 2022-03-09 13:44 UTC
Labels: bug
