### ISSUE TITLE
Cross-Cluster List Flake: cannot watch across logical clusters for a resource type with several distinct schemas

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#297] opened 2021-12-06 18:02 UTC
Rarely, we see the following when starting informers based on the cross-cluster client for the workspace controller. We install the CRD into every logical cluster using an identical definition we load from YAML in this repo, so it is not possible for there to be any difference in schema. Ideally, the error would be improved to show what the perceived difference was (or logged at the k8s level).

```
E1206 08:25:57.535530   42874 reflector.go:138] k8s.io/client-go@v0.0.0-20211203153731-1f4695370a63/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkspaceShard: failed to list *v1alpha1.WorkspaceShard: Internal error occurred: error resolving resource: cannot watch across logical clusters for a resource type with several distinct schemas
```

**Comment by jmprusi** [comment] 2021-12-15 13:11
@stevekuznetsov looks like the code producing that error has changed substantially (How the comparison is handled, etc.), are you still able to reproduce it ?

**Comment by ncdc** [comment] 2021-12-15 14:17
@jmprusi while the code has moved around as part of #302, I don't think the comparison code has changed?

**Comment by jmprusi** [comment] 2021-12-15 14:28
@ncdc true! couldn't find it. thanks!

**Comment by stevekuznetsov** [comment] 2021-12-15 15:12
That being said, I have also not been able to reproduce again :)

**Comment by ncdc** [comment] 2021-12-15 15:20
I had it happen to me once or twice locally, but I haven't been able to reproduce ☹️

**Comment by ncdc** [comment] 2022-02-23 20:04
I haven't seen this in a long time. Closing. Will reopen if needed.

**Closed by ncdc** 2022-02-23 20:04 UTC
Labels: bug, severity/timebomb
