### ISSUE TITLE
How to handle the CRD conflict in mutiple cluster scenario

### ISSUE THREAD

**Issue by vincent-pli** [kcp-dev/kcp#89] opened 2021-05-18 07:10 UTC
I have tested `kcp` with two kubernetes cluster, and sync CRD by default(deployment and pod).

I think the CRDs is exactly the same one, see it's `deployment` and `pod`, but actually not, the `deployment` come from different cluster has different `.spec`(one cluser is v1.19.x another is v1.20.x), so they are treat as different thing and keeping replace each other(since with same name).

So I wonder to know, by design what's the behavior is such scenario?

**Comment by davidfestal** [comment] 2021-05-18 10:20
As I had mentioned in the [PR that integrated the CRD puller in the cluster controller](https://github.com/kcp-dev/kcp/pull/20), this is for now a very basic implementation of API resource import from external clusters, **with no negociation at all in case of resource schema conflicts**.

There should be some sort of schema negotiation when the same API resource is imported into a KCP logical cluster from several sources. We'll need to diff the various schemas and, when possible, finally use the least-common-denominator (LCD) of the various imported schemas. Some details of how this should be driven and managed are still to be defined and I'll let @smarterclayton complete / correct what I briefly answered here.

But to summarize: No the current behavior is not by design, and API resource import **and negotiation** is a key point of KCP that still needs to be fully specified & implemented.

**Comment by davidfestal** [comment] 2021-05-18 10:53
For more details about CRD negotiation, see https://github.com/kcp-dev/kcp/blob/main/docs/investigations/logical-clusters.md#crd-virtualization-inheritance-and-normalization

**Comment by vincent-pli** [comment] 2021-05-20 00:33
Thanks @davidfestal 
Expect to see the design details.

**Comment by davidfestal** [comment] 2021-08-12 14:54
This should have been fixed by PR #116

**Closed** 2021-08-12 14:54 UTC
